#!/usr/bin/bash

openssl ecparam -out ./ecc/ecc.ca.key.pem -name prime256v1 -genkey
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:TRUE") -new -nodes -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=ACSECUTIC" -x509 -extensions ext -sha256 -key ./ecc/ecc.ca.key.pem -text -out ./ecc/ecc.ca.cert.pem
openssl ecparam -out ./ecc/ecc.serveur.key.pem -name prime256v1 -genkey
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=localhost" -reqexts ext -sha256 -key ./ecc/ecc.serveur.key.pem -text -out ./ecc/ecc.csr.pem
openssl x509 -req -days 3650 -CA ./ecc/ecc.ca.cert.pem -CAkey ./ecc/ecc.ca.key.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ./ecc/ecc.csr.pem -text -out ./ecc/ecc.serveur.pem
openssl x509 -in ./ecc/ecc.serveur.pem -noout -pubkey > ./ecc/ecc.serveur.pubkey.pem
cat ./ecc/ecc.serveur.key.pem ./ecc/ecc.serveur.pem > ./ecc/bundle_serveur.pem
